In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

## ReplayBuffer class

In [12]:
x = 4
y = 5
#print(torch.zeros((x,)+y).to(device))
print(torch.zeros(x,y))
# torch.int64=torch.long
(x,) + y

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


TypeError: can only concatenate tuple (not "int") to tuple

### sample function

In [20]:
A = np.random.rand(3,3)
print(torch.from_numpy(A))
print(torch.tensor(A))

tensor([[0.9959, 0.8286, 0.1436],
        [0.8537, 0.3497, 0.0434],
        [0.1321, 0.9138, 0.2528]], dtype=torch.float64)
tensor([[0.9959, 0.8286, 0.1436],
        [0.8537, 0.3497, 0.0434],
        [0.1321, 0.9138, 0.2528]], dtype=torch.float64)


In [113]:
a = [i for i in range(10)]
b = torch.tensor(a,dtype = torch.float)
sig=nn.Sigmoid()
b=np.array(sig(b))
b/=b.sum()
l = []
for i in range(10**5):
    l.append(int(np.random.choice(a,1,p=b)))
c = np.zeros(10)
for i in range(10):
    c[i] = l.count(i)

c /= c.sum()

In [114]:
print("c=",c,"\n\nb=",b)
print("\nerror=" ,(abs(c-b)).sum())

c= [0.055266 0.081056 0.097472 0.10511  0.109052 0.109543 0.110329 0.110593
 0.110536 0.111043] 

b= [0.05533478 0.08090593 0.09747741 0.10542095 0.10867903 0.10992886
 0.11039592 0.11056874 0.11063244 0.1106559 ]

error= 0.0018687650208473253


### update error

In [131]:
e = torch.rand(3,4,5)
e.detach().shape # detach from gpu
e = e.sum()
e.numpy()

array(32.970886, dtype=float32)

In [149]:
l = np.zeros((10, 1), dtype=np.float)
l[:4] = torch.rand(4,1).numpy() # necessary to match the size 

## Agent

In [150]:
import numpy as np
import random
from collections import namedtuple, deque
import itertools

import torch
import torch.nn.functional as F
import torch.optim as optim

In [152]:
seed = random.seed(42)

In [173]:
T = torch.from_numpy(np.random.rand(3,1))
T1=T.unsqueeze(0) # what if use 1 or 2 instead of 0 ?
print((T).shape)
print(T1.shape)



torch.Size([3, 1])
torch.Size([1, 3, 1])


### act

In [184]:
x = torch.randn(3, requires_grad=True)
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)
# visit https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#gradients

True
True
False


In [186]:
print(np.argmax(x.data.numpy()))
print(x)

2
tensor([-0.6811, -0.9251, -0.2685], requires_grad=True)


In [189]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### update error

In [239]:
t = torch.tensor([[1,2],[3,4],[5,6]])
g = torch.tensor([[0,0],[1,2],[2,1],[1,1]])
h = torch.tensor([[0,1,0],[1,1,1],[1,0,0]])
print(t,"\n\n",g,"\n\n",h,"\n")
print(t.gather(0, g) ,"\n\n",t.gather(-1, h))

tensor([[1, 2],
        [3, 4],
        [5, 6]]) 

 tensor([[0, 0],
        [1, 2],
        [2, 1],
        [1, 1]]) 

 tensor([[0, 1, 0],
        [1, 1, 1],
        [1, 0, 0]]) 

tensor([[1, 2],
        [3, 6],
        [5, 4],
        [3, 4]]) 

 tensor([[1, 2, 1],
        [4, 4, 4],
        [6, 5, 5]])


In [241]:
done = True
none = False
1-done
1-none

1

## train agent

In [249]:
d = deque(maxlen=3)
d.append(3)
d.append(4)
d.append(5)

In [250]:
print(d)
d.append(7)
print(d)

deque([3, 4, 5], maxlen=3)
deque([4, 5, 7], maxlen=3)


In [251]:
(4,)+(95, 128)

(4, 95, 128)

In [255]:
(4,) + (5,)

tensor([0.3912, 0.5234, 0.0063])

In [273]:
d.append(np.copy(torch.rand(3,3)))

In [278]:
np.shape(np.array(d))

(3, 3, 3)

In [283]:
6//2
6/2

3.0